/**
 * mocks.ts — Mock Strava Data for Local Development
 */

export const MOCK_ACTIVITIES = [
    {
        "resource_state": 2,
        "athlete": { "id": 134004511, "resource_state": 1 },
        "name": "Carrera por la mañana",
        "distance": 8015.9,
        "moving_time": 2141,
        "elapsed_time": 2141,
        "total_elevation_gain": 25,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "device_name": "Garmin Forerunner 970",
        "id": 17854642739,
        "start_date": "2026-03-25T15:14:57Z",
        "start_date_local": "2026-03-25T09:14:57Z",
        "timezone": "(GMT-06:00) America/Mexico_City",
        "utc_offset": -21600,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 12,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": { "id": "a17854642739", "summary_polyline": "", "resource_state": 2 },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": true,
        "visibility": "only_me",
        "flagged": false,
        "gear_id": "g21567082",
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 3.744,
        "max_speed": 5.34,
        "average_cadence": 82.9,
        "average_temp": 22,
        "average_watts": 397.9,
        "max_watts": 488,
        "weighted_average_watts": 397,
        "device_watts": true,
        "kilojoules": 852.1,
        "has_heartrate": true,
        "average_heartrate": 163.2,
        "max_heartrate": 176,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 2254.8,
        "elev_low": 2244,
        "upload_id": 18954150127,
        "upload_id_str": "18954150127",
        "external_id": "garmin_ping_550462666873",
        "from_accepted_tag": false,
        "pr_count": 3,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": { "id": 134004511, "resource_state": 1 },
        "name": "Vuelta ciclista por la mañana",
        "distance": 5000.8,
        "moving_time": 1861,
        "elapsed_time": 2124,
        "total_elevation_gain": 29,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": null,
        "device_name": "Garmin Forerunner 970",
        "id": 17843005763,
        "start_date": "2026-03-24T16:52:12Z",
        "start_date_local": "2026-03-24T10:52:12Z",
        "timezone": "(GMT-06:00) America/Mexico_City",
        "utc_offset": -21600,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 1,
        "kudos_count": 8,
        "comment_count": 2,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a17843005763",
            "summary_polyline": "kgouBbtg|Qg@QI@MFc@Bo@VQBUCY@}BPaCj@k@@iATQFMA[De@LsAXUBc@@aARsANc@Jk@Fc@LQHUDS?wAWiBj@aAl@}Al@ODS@KJWLmAd@{BdAYBY}@_AaCkAiDAKTaABc@Gq@EMo@kAc@UWGUA_@MGO_ByEc@kAg@gAAOQq@Ue@_@{@?sAK_@Oa@c@a@SI@BA?@E@??DEA[gAYi@a@kAMWi@_B_@o@i@uBe@iA@KB?@DE@CAAMaBeCcAiCWk@c@g@Ug@Oa@GK[eAk@oAi@{AGIK_@{B}FIc@Nk@Dk@C]GQ]]QKSEi@UWHINUp@OLU@{@Gu@M{E]k@Cw@@gAOs@CgAYwAg@yEqAyC_AcAa@iD_As@YaAQcGQi@G[MHe@NsB@QEA@B@ABOGIFa@EI[IMIGGEGc@Em@SE]B_@J[NcA?MJy@?YX_B",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [19.415602, -99.167419],
        "end_latlng": [19.442999, -99.148157],
        "average_speed": 2.687,
        "max_speed": 8.22,
        "average_watts": 29.5,
        "device_watts": false,
        "kilojoules": 55,
        "has_heartrate": true,
        "average_heartrate": 96.6,
        "max_heartrate": 128,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 2260.2,
        "elev_low": 2237,
        "upload_id": 18942472287,
        "upload_id_str": "18942472287",
        "external_id": "garmin_ping_550093188496",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": { "id": 134004511, "resource_state": 1 },
        "name": "Carrera por la mañana",
        "distance": 6459.4,
        "moving_time": 2091,
        "elapsed_time": 2232,
        "total_elevation_gain": 23,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "device_name": "Garmin Forerunner 970",
        "id": 17841373275,
        "start_date": "2026-03-24T14:32:27Z",
        "start_date_local": "2026-03-24T08:32:27Z",
        "timezone": "(GMT-06:00) America/Mexico_City",
        "utc_offset": -21600,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 0,
        "kudos_count": 14,
        "comment_count": 0,
        "athlete_count": 2,
        "photo_count": 0,
        "map": {
            "id": "a17841373275",
            "summary_polyline": "oxpuB`wh|QZp@Nd@R`@\\jAP`@LTj@|AXh@XL@BBP?VEV@TDd@VtAdDbJV|@^`ARp@?RUxBLjAI^[v@K`@Y`C@fABv@b@lC`@~ATjA\\|BDn@HzB?pABfAAlBBpAFxACd@DbA@jBN`CJ~@Lr@L\\p@dAn@v@bAh@tAXp@Hz@FjA?hAMrA_@l@]t@g@l@o@R[^_AT}@Rg@TkARu@J{@RmAj@wEJuB@iACo@i@gE[eAs@iBe@aAe@{AIc@Cm@@o@E{BI_@Oa@ISSWq@c@qAm@eAa@m@]y@YaDgBYW[OUEIA{@Bg@BMDs@b@o@l@{@nAWh@K\\Qr@E^SfCB`AXbCTt@Jn@N`@R|@^dDFrDDr@Ad@D`AAlADvBA\\FhDAf@Dj@DRJ|AL~@Rt@f@bAj@x@j@b@d@RvAZjANd@BnACPEf@EbAQrAw@x@o@RUT_@l@yAl@mCDiAZyAb@aDHiAR}B?w@R_AAWUwBYaBOi@m@{AGIm@wAa@sAKwA?}CQo@",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": "g21567082",
        "start_latlng": [19.424763, -99.17228],
        "end_latlng": [19.418183, -99.180334],
        "average_speed": 3.089,
        "max_speed": 5.72,
        "average_cadence": 83.4,
        "average_temp": 21,
        "average_watts": 324.2,
        "max_watts": 595,
        "weighted_average_watts": 328,
        "device_watts": true,
        "kilojoules": 678,
        "has_heartrate": true,
        "average_heartrate": 143.5,
        "max_heartrate": 172,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 2254.4,
        "elev_low": 2240.4,
        "upload_id": 18940832157,
        "upload_id_str": "18940832157",
        "external_id": "garmin_ping_550053514622",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": { "id": 134004511, "resource_state": 1 },
        "name": "Carrera por la mañana",
        "distance": 12020.9,
        "moving_time": 3531,
        "elapsed_time": 3531,
        "total_elevation_gain": 37,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "device_name": "Garmin Forerunner 970",
        "id": 17767984029,
        "start_date": "2026-03-18T14:49:49Z",
        "start_date_local": "2026-03-18T08:49:49Z",
        "timezone": "(GMT-06:00) America/Mexico_City",
        "utc_offset": -21600,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 11,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": { "id": "a17767984029", "summary_polyline": "", "resource_state": 2 },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": true,
        "visibility": "only_me",
        "flagged": false,
        "gear_id": "g21567082",
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 3.404,
        "max_speed": 4.12,
        "average_cadence": 87,
        "average_temp": 23,
        "average_watts": 356,
        "max_watts": 448,
        "weighted_average_watts": 358,
        "device_watts": true,
        "kilojoules": 1257,
        "has_heartrate": true,
        "average_heartrate": 147,
        "max_heartrate": 166,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 2254.4,
        "elev_low": 2244.4,
        "upload_id": 18866895309,
        "upload_id_str": "18866895309",
        "external_id": "garmin_ping_547707523832",
        "from_accepted_tag": false,
        "pr_count": 4,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": { "id": 134004511, "resource_state": 1 },
        "name": "Vuelta ciclista por la mañana",
        "distance": 3363.1,
        "moving_time": 711,
        "elapsed_time": 769,
        "total_elevation_gain": 3,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": null,
        "device_name": "Garmin Forerunner 970",
        "id": 17755152895,
        "start_date": "2026-03-17T15:11:56Z",
        "start_date_local": "2026-03-17T09:11:56Z",
        "timezone": "(GMT-06:00) America/Mexico_City",
        "utc_offset": -21600,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 0,
        "kudos_count": 5,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a17755152895",
            "summary_polyline": "uaquBz_h|Q_AqCi@wA@URs@BU@WIo@A?AISe@Y]UMa@Kk@IIEMSa@oA_AiCc@gAWm@GGcAyCMi@@yA[u@MOo@a@gFaNc@{AuAwBoAaDQYk@{@Sc@{@eC]u@M_@_@u@]eA_@}@aAkCIa@?QJq@Dg@CSIWKO[Yy@WMSEAQNo@vAY@UAQGiAMuBQ}AGs@Mg@AME[Su@Ea@Fg@Ac@GkBm@}C{@_Cu@_@OiF}AuAg@_AQW@eFS",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [19.424672, -99.171475],
        "end_latlng": [19.442475, -99.151589],
        "average_speed": 4.73,
        "max_speed": 7.25,
        "average_watts": 44.5,
        "device_watts": false,
        "kilojoules": 31.6,
        "has_heartrate": true,
        "average_heartrate": 108.2,
        "max_heartrate": 127,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 2242.8,
        "elev_low": 2235.4,
        "upload_id": 18854029009,
        "upload_id_str": "18854029009",
        "external_id": "garmin_ping_547309552815",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": { "id": 134004511, "resource_state": 1 },
        "name": "Carrera por la mañana",
        "distance": 6706.6,
        "moving_time": 2113,
        "elapsed_time": 2386,
        "total_elevation_gain": 17,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "device_name": "Garmin Forerunner 970",
        "id": 17754878642,
        "start_date": "2026-03-17T14:15:42Z",
        "start_date_local": "2026-03-17T08:15:42Z",
        "timezone": "(GMT-06:00) America/Mexico_City",
        "utc_offset": -21600,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 0,
        "kudos_count": 14,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a17754878642",
            "summary_polyline": "ggsuB|bd|QrD|@~@l@NRl@fAj@|A|@lBvAfE^`A^nAZj@hApD^|B`@z@\\XNVf@nA^lAn@~AFZTd@b@jAt@fBp@dCHv@Jh@Fd@TlAv@vBf@~@bA~Ct@pBp@vAd@zA^`ANr@@bALl@PVj@d@n@dAl@tAZfAjAxCh@bBRh@DP@RSt@Cd@@ZFj@JPFDr@Fn@Nl@FHBLH^t@xCpIj@vAj@nADBD@j@KN?NBl@TVXDL@\\Ez@@t@b@nAp@|ABP?JFJ^z@jA`Df@hA~@~A@RCx@PzAvArDb@vAvAxDl@vBEhAFl@@fAIXYt@YnAQ~AApAFfAHj@TrAn@rC\\`CJ~@FrABfADlJHxFFrAVfCPz@NZx@hAl@h@h@XxAd@fBNX?hAEt@IXEx@Wx@c@n@e@p@q@T_@To@d@_Bf@_Cr@{Df@cFBw@?_BAm@Iw@OoAWqAo@kBy@oBk@iBGq@EwDGi@Um@U_@e@]eB}@}@]e@MmBaA",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": "g21567082",
        "start_latlng": [19.437654, -99.149227],
        "end_latlng": [19.420585, -99.179114],
        "average_speed": 3.174,
        "max_speed": 4.76,
        "average_cadence": 86,
        "average_temp": 22,
        "average_watts": 326.2,
        "max_watts": 521,
        "weighted_average_watts": 317,
        "device_watts": true,
        "kilojoules": 688.8,
        "has_heartrate": true,
        "average_heartrate": 134.8,
        "max_heartrate": 160,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 2253.4,
        "elev_low": 2237.2,
        "upload_id": 18853753817,
        "upload_id_str": "18853753817",
        "external_id": "garmin_ping_547301343298",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": { "id": 134004511, "resource_state": 1 },
        "name": "Carrera por la mañana",
        "distance": 6786.8,
        "moving_time": 2117,
        "elapsed_time": 2213,
        "total_elevation_gain": 21,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "device_name": "Garmin Forerunner 970",
        "id": 17708882428,
        "start_date": "2026-03-13T14:38:05Z",
        "start_date_local": "2026-03-13T08:38:05Z",
        "timezone": "(GMT-06:00) America/Mexico_City",
        "utc_offset": -21600,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 4,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": { "id": "a17708882428", "summary_polyline": "", "resource_state": 2 },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": true,
        "visibility": "only_me",
        "flagged": false,
        "gear_id": "g21567082",
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 3.206,
        "max_speed": 5.88,
        "average_cadence": 83.5,
        "average_temp": 21,
        "average_watts": 331.4,
        "max_watts": 537,
        "weighted_average_watts": 351,
        "device_watts": true,
        "kilojoules": 695.4,
        "has_heartrate": true,
        "average_heartrate": 146.3,
        "max_heartrate": 174,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 2256,
        "elev_low": 2245.8,
        "upload_id": 18807427121,
        "upload_id_str": "18807427121",
        "external_id": "garmin_ping_545759139717",
        "from_accepted_tag": false,
        "pr_count": 1,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": { "id": 134004511, "resource_state": 1 },
        "name": "Carrera por la mañana",
        "distance": 9010.4,
        "moving_time": 2673,
        "elapsed_time": 2673,
        "total_elevation_gain": 29,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "device_name": "Garmin Forerunner 970",
        "id": 17685729486,
        "start_date": "2026-03-11T14:03:46Z",
        "start_date_local": "2026-03-11T08:03:46Z",
        "timezone": "(GMT-06:00) America/Mexico_City",
        "utc_offset": -21600,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 9,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": { "id": "a17685729486", "summary_polyline": "", "resource_state": 2 },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": true,
        "visibility": "only_me",
        "flagged": false,
        "gear_id": "g21567082",
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 3.371,
        "max_speed": 4,
        "average_cadence": 90.3,
        "average_temp": 22,
        "average_watts": 347.3,
        "max_watts": 420,
        "weighted_average_watts": 348,
        "device_watts": true,
        "kilojoules": 928.7,
        "has_heartrate": true,
        "average_heartrate": 147.6,
        "max_heartrate": 164,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 2256,
        "elev_low": 2243.6,
        "upload_id": 18784170615,
        "upload_id_str": "18784170615",
        "external_id": "garmin_ping_544986961943",
        "from_accepted_tag": false,
        "pr_count": 3,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": { "id": 134004511, "resource_state": 1 },
        "name": "Carrera por la mañana",
        "distance": 8605.1,
        "moving_time": 2567,
        "elapsed_time": 2567,
        "total_elevation_gain": 19,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "device_name": "Garmin Forerunner 970",
        "id": 17673436611,
        "start_date": "2026-03-10T14:38:29Z",
        "start_date_local": "2026-03-10T08:38:29Z",
        "timezone": "(GMT-06:00) America/Mexico_City",
        "utc_offset": -21600,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 4,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": { "id": "a17673436611", "summary_polyline": "", "resource_state": 2 },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": true,
        "visibility": "only_me",
        "flagged": false,
        "gear_id": "g21567082",
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 3.352,
        "max_speed": 5.74,
        "average_cadence": 85.4,
        "average_temp": 24,
        "average_watts": 354,
        "max_watts": 543,
        "weighted_average_watts": 359,
        "device_watts": true,
        "kilojoules": 908.8,
        "has_heartrate": true,
        "average_heartrate": 155.9,
        "max_heartrate": 177,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 2254.4,
        "elev_low": 2243.6,
        "upload_id": 18771838744,
        "upload_id_str": "18771838744",
        "external_id": "garmin_ping_544606623951",
        "from_accepted_tag": false,
        "pr_count": 2,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": { "id": 134004511, "resource_state": 1 },
        "name": "Carrera por la mañana",
        "distance": 8068.3,
        "moving_time": 2670,
        "elapsed_time": 4445,
        "total_elevation_gain": 22,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "device_name": "Garmin Forerunner 970",
        "id": 17650094060,
        "start_date": "2026-03-08T14:01:15Z",
        "start_date_local": "2026-03-08T08:01:15Z",
        "timezone": "(GMT-06:00) America/Mexico_City",
        "utc_offset": -21600,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 0,
        "kudos_count": 12,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a17650094060",
            "summary_polyline": "gcquB|`h|Q{@aCOm@Yo@Um@?WL[Ha@BS?SGe@IKe@]c@OI?O@OEMIEIEa@Q]{@uCQc@_@s@sBwFEc@Lc@DU?SE[ISU]}@SUSO[W}@]}@OW]sA[o@Uu@iAkCYcA]i@[}@WgACWIM?QQo@Sc@k@q@[m@I]Ca@_@w@sAaEi@oAeAsCW_AJm@Dc@?e@EOIMYUSKUEWSIAM@SZWPGRGJIFI?k@GBIGBQ?a@Ga@AoEYuAC]Ei@CqAOyAo@cG_BeEsAaEcA}@_@s@OQIaA{@E?GEq@WUWIC_@Em@UAOJiAAYR}ACi@EO?QNeAAc@V{AJiATsAgAY|@PAI@QH[PAEK@UHs@FK?SLaAHkADs@PiB@a@V}BP{BDKPURe@Ni@JKJCh@?^EXFDB^d@bAdAjAtApApAb@j@|@fAjBtBFB`BlCVf@T\\h@tAp@bATf@p@hAd@hAXzAPR\\TRZzArChAtCn@|BDVZp@~CvIRtAJd@JRXZLVPRPZdA`Dt@hBVd@rA~DHPHDH?VOLAPDRN|@lAN^Lb@f@l@R^n@dB@x@Kd@F^d@pAJPb@zAHLRd@Nn@NTHVlAdCTr@PR^HZRHL?DTZDP@VARQl@B^FJRf@l@xANl@f@nAXz@Tf@Tz@l@tALf@DDJAV?f@J\\XNVPj@BREb@Sf@Eb@@JT`@p@vB`@x@Tn@|@tBV|@n@xATr@DF^RRXF\\I`A?^hAfCV|@^z@f@xA",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": "g21567082",
        "start_latlng": [19.424959, -99.171206],
        "end_latlng": [19.423166, -99.176086],
        "average_speed": 3.022,
        "max_speed": 4.52,
        "average_cadence": 86.7,
        "average_temp": 23,
        "average_watts": 308.9,
        "max_watts": 463,
        "weighted_average_watts": 295,
        "device_watts": true,
        "kilojoules": 824.2,
        "has_heartrate": true,
        "average_heartrate": 136.7,
        "max_heartrate": 163,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 2246.8,
        "elev_low": 2228,
        "upload_id": 18748331542,
        "upload_id_str": "18748331542",
        "external_id": "garmin_ping_543820078675",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    }
];
